steps:
  - name: gcr.io/cloud-builders/docker
    id: Build image
    args:
      [
        'build',
        '-t',
        '${_REGION}-docker.pkg.dev/$PROJECT_ID/${_AR_REPO}/${_SERVICE}:$COMMIT_SHA',
        './my_app'
      ]

  - name: gcr.io/cloud-builders/docker
    id: Push image
    args:
      [
        'push',
        '${_REGION}-docker.pkg.dev/$PROJECT_ID/${_AR_REPO}/${_SERVICE}:$COMMIT_SHA'
      ]

  - name: gcr.io/google.com/cloudsdktool/cloud-sdk
    id: Deploy to Cloud Run
    entrypoint: gcloud
    args:
      [
        'run',
        'deploy',
        '${_SERVICE}',
        '--image',
        '${_REGION}-docker.pkg.dev/$PROJECT_ID/${_AR_REPO}/${_SERVICE}:$COMMIT_SHA',
        '--region',
        '${_REGION}',
        '--platform',
        'managed',
        '--allow-unauthenticated'
      ]

images:
  - '${_REGION}-docker.pkg.dev/$PROJECT_ID/${_AR_REPO}/${_SERVICE}:$COMMIT_SHA'
